/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnaexample_NativeClient_Setup */

#ifndef _Included_jnaexample_NativeClient_Setup
#define _Included_jnaexample_NativeClient_Setup
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnaexample_NativeClient_Setup
 * Method:    init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_ca_weblite_objc_RuntimeUtils_init
  (JNIEnv *, jclass);
    
/*
 * Class:     jnaexample_NativeClient_Setup
 * Method:    createProxy
 * Signature: (Ljnaexample/NativeClient;)J
 */
JNIEXPORT jlong JNICALL Java_ca_weblite_objc_RuntimeUtils_createProxy
(JNIEnv *, jclass, jobject);
    
/*
 * Class:     jnaexample_NativeClient_Setup
 * Method:    getJavaPeer
 * Signature: (Ljnaexample/NativeClient;)J
 */
JNIEXPORT jobject JNICALL Java_ca_weblite_objc_RuntimeUtils_getJavaPeer
(JNIEnv *, jclass, jlong);
    
/*
JNIEXPORT jobject JNICALL Java_ca_weblite_objc_RuntimeUtils_invokeWithSelfAndTarget
(JNIEnv *, jclass, jlong, jlong, jlong);
*/
#ifdef __cplusplus
}
#endif
#endif
